### ISSUE TITLE
Bespin-mailer stuck 

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-mailer#1]
Last week, the `bespin-mailer` container on bespin dev got stuck. Restarting the container caused ~40 emails to be delivered at once.

Let's investigate why this service needs restarting

**Comment by johnbradley** [comment]
We had a similar issue with lando not reading messages from the queue.
Looking at the message queue on the server running rabbit:
```
$ sudo rabbitmqctl list_queues name messages_ready state messages_unacknowledged
Listing queues ...
EmailQueue	0	running	0
RetryQueue	0	running	0
amq.gen-Yto6m2lnqt3JgIRmN5lJeQ	0	running	0
lando	1	running	0
```
There is a message sitting in the queue ready for lando to claim.

If I list the connections I can see lando and the job watcher are both connected to rabbitmq.
```rabbitmqctl list_connections```

**Comment by johnbradley** [comment]
Similar sounding issue:
https://github.com/pika/pika/issues/297

**Comment by johnbradley** [comment]
Don't know if it's related but there is a message in `var/log/rabbitmq/rabbit@bespin-rabbit...`
```
=WARNING REPORT==== 18-Dec-2017::21:21:22 ===
closing AMQP connection <0.9038.448> (...lando ip... -> ...rabbit ip...):
client unexpectedly closed TCP connection
```

**Comment by dleehr** [comment]
Seems like a plausible explanation - the connection timed out but the client doesn't know. Does it sound like the heartbeat setting might fix this? Or do we need to switch to async as mentioned in the pika issue?

**Comment by johnbradley** [comment]
We are already specifying the heartbeat setting:
```
        connection_params = pika.ConnectionParameters(host=self.host, credentials=credentials, 
                   heartbeat_interval=0)
        self.connection = pika.BlockingConnection(connection_params)
```
https://github.com/Duke-GCB/lando-messaging/blob/7d42270f9fbfb55753400a1373f01825a8de714f/lando_messaging/workqueue.py#L49-L50

There is also a newer version of pika available now.

**Comment by johnbradley** [comment]
I think we should upgrade to the latest pika and switch to the async method.
